### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by HangingWithCMM** [kyeondiscord/ip-grabber-creator#4]
I don't get the info after someone runs it

**Comment by BillyHri** [comment]
Hi,

This is an informant, at Proswapper CEO.
I am speaking on behalf of KyeOnDiscord, to inform you that this issue has been resolved.
If you have any further complaints please talk to my assistant.

Thanks,
BillyHri

**Comment by HangingWithCMM** [comment]
Ok thanks

**Comment by KyeOnDiscord** [comment]
L

**Comment by HangingWithCMM** [comment]
Why L
